### ISSUE TITLE
"issueベースの開発"のレビュー依頼

### ISSUE THREAD

**Issue by kame82** [kame82/portfolio#26]

**Comment by kame82** [comment]
## サービス概要

- Web 制作における HTML、CSS、JavaScript などのコードの保管管理が出来るサービス。
- これまで実装したアイテム（ボタンやハンバーガーメニューなど）のコードを保存しておき、必要時に呼び起こして閲覧することで、実装時の時短が可能となる。
- 記載したコードはリアルタイム編集とプレビューのリアルタイム同期により、即時確認可能 →code pen のような使い方が可能。

### README に記載した機能

MVP リリース項目

- [] ユーザー登録機能
- [] ログイン機能
- [] パスワード変更機能
- [] 記事(コード)投稿機能
- [] 記事閲覧機能（未ログインでも閲覧可能）
- [] 記事編集機能
- [] 記事削除機能
- [] いいね機能
- [] いいね解除機能
- [] 対象言語：HTML, CSS, Javascript
- [] プライベート投稿機能

本リリース項目

- [] タグ投稿機能
- [] タグ編集機能
- [] タグ削除機能

必要なページ

- [] トップページ
- [ ] コード一覧画面
- [ ] ログイン画面
- [ ] ユーザー登録画面
- [ ] コード編集画面
- [ ] 利用規約
- [ ] プライバシーポリシー

**Comment by ippei-shimizu** [comment]
ご提出ありがとうございます！
こちらを参考にし、GithubProjectsを使用してissueにストーリーポイントを設定した形のURLも一緒に記載していただき、再提出をお願いいたします。
https://school.runteq.jp/v3/curriculums/application_development/chapters/11

**Comment by kame82** [comment]
ご確認ありがとうございました。

Github Projectsがprivateになっていた事が原因かもしれません。以下確認出来ますでしょうか？
再度ご確認のほどよろしくお願いします。

https://github.com/users/kame82/projects/1/views/1

**Comment by kenchasonakai** [comment]
LGTMです！

ストーリーポイントが大きいものがあると思うので、よくわかっておらず大きくなってしまっているのであれば事前に実装イメージがしっかりつくように調べる、いろいろな機能が混ざってしまって大きく成っているのであれば分解して小さく作っていくのがおすすめです

**Comment by kame82** [comment]
承知しました！ご確認いただきありがとうございました
